# Generated by Django 3.0.6 on 2020-06-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_cep', models.CharField(max_length=8)),
                ('endereco_logradouro', models.CharField(max_length=255)),
                ('endereco_complemento', models.CharField(max_length=128)),
                ('endereco_numero', models.CharField(max_length=10)),
                ('endereco_bairro', models.CharField(max_length=255)),
                ('endereco_cidade', models.CharField(max_length=255)),
                ('endereco_estado', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome_empresa', models.CharField(max_length=255)),
                ('fornecedor_cnpj', models.CharField(max_length=14)),
                ('fornecedor_email', models.EmailField(max_length=254)),
                ('fornecedor_site', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_ddd', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('phone_type', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
