# Generated by Django 3.0.3 on 2020-06-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientesapp.Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='client_phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientesapp.Phone'),
            preserve_default=False,
        ),
    ]
