# Generated by Django 3.0.3 on 2020-06-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0002_auto_20200604_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_endereco',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientesapp.Client'),
            preserve_default=False,
        ),
    ]
