# Generated by Django 3.0.3 on 2020-06-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0003_auto_20200604_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='phone_client',
        ),
    ]
