# Generated by Django 3.0.3 on 2020-06-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0005_phone_phone_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientesapp.Client'),
        ),
    ]
