# Generated by Django 3.0.8 on 2020-07-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0006_auto_20200604_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='phone_client',
        ),
    ]
