# Generated by Django 3.0.8 on 2020-07-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientesapp', '0008_phone_phone_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_client',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_type',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='client',
            name='client_endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientesapp.Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='client_phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientesapp.Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco_cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco_numero',
            field=models.IntegerField(),
        ),
    ]
